// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
export default function handler(req, res) {
  res.status(200).json({
    advice_answers: [
      {
        question: "What is the best time to visit?",
        answer: "The best time to visit is during the spring."
      },
      {
        question: "How can I get travel insurance?",
        answer: "You can get travel insurance online or through a travel agent."
      },
      {
        question: "What should I pack?",
        answer: "Pack light clothing and a jacket for cooler evenings."
      },
      {
        question: "Is the water safe to drink?",
        answer: "Tap water is generally safe, but bottled water is recommended."
      },
      {
        question: "How do I get around the city?",
        answer: "The city has a reliable public transportation system."
      },
      {
        question: "What is the local language?",
        answer: "The local language is Spanish, but English is widely spoken."
      },
      {
        question: "Are there any cultural customs I should know?",
        answer:
          "It's customary to greet people with a handshake or a kiss on the cheek."
      },
      {
        question: "Can I use my credit card?",
        answer:
          "Credit cards are widely accepted, but it's good to carry some cash."
      }
    ],
    general_faqs: [
      {
        question: "What currency is used?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "Do I need a visa?",
        answer:
          "Visa requirements are determined by various factors including your nationality, the country you wish to visit, and the purpose and duration of your stay. Generally, if you're traveling internationally, you might need a visa depending on these variables.For example, if you are a U.S. citizen planning to visit most European countries, you may not need a visa for short stays, such as for tourism or business, due to agreements like the Schengen Visa Waiver. However, for longer stays or specific purposes like work or study, you would likely need to apply for a visa.On the other hand, if you are traveling to a country like China or India, a visa is usually required regardless of your nationality. Each country has its own visa policies which can include requirements such as invitations, proof of financial means, and details of your stay.Visa policies can also vary for different types of travelers, such as students, workers, or tourists, and may include additional documentation or approvals. It's always best to check the specific visa requirements for your destination country well in advance of your travel date. You can do this by contacting the embassy or consulate of the country you plan to visit or by visiting their official immigration website for the most current and detailed information.Keep in mind that visa regulations are subject to change, and it's important to verify the most up-to-date requirements before making any travel plans."
      },
      {
        question: "What is the time zone?",
        answer:
          "Time zones are standardized regions of the Earth that have the same local time. They are used to synchronize clocks across different regions and are typically based on the longitudinal position of the area. The Earth is divided into 24 time zones, each approximately 15 degrees of longitude apart, reflecting the Earth's rotation, which causes different areas to experience daylight and darkness at different times. Each time zone is defined by its offset from Coordinated Universal Time (UTC), which is the time standard used globally. For example, some common time zones include: - **UTC-12:00**: The time zone for Baker Island, an uninhabited island in the central Pacific Ocean. - **UTC-05:00**: Eastern Standard Time (EST), used in places like New York and Toronto during the winter months. During daylight saving time, this becomes Eastern Daylight Time (EDT). - **UTC+00:00**: Greenwich Mean Time (GMT), which is the standard time zone used as a reference point for coordinating time globally. It is also referred to as Coordinated Universal Time (UTC) when discussing time zones. - **UTC+09:00**: Japan Standard Time (JST), which is used in Japan and does not observe daylight saving time. - **UTC+10:00**: Australian Eastern Standard Time (AEST), used in eastern Australia. During daylight saving time, this becomes Australian Eastern Daylight Time (AEDT). Time zones can be influenced by political and regional decisions. Some countries or regions may adjust their clocks for daylight saving time, shifting the time zone by one hour during certain periods of the year. This adjustment is made to better align daylight hours with the typical working day, thereby optimizing the use of natural daylight and conserving energy. In addition to standard time zones, there are also several special time zones that do not fit neatly into the 24-hour framework. These can include fractional hour offsets, such as Indian Standard Time (IST), which is UTC+05:30, and Nepal Time (NPT), which is UTC+05:45. To determine the time zone for a specific location, you can use various online tools and resources, such as world clocks, time zone converters, and geographical databases. These tools can help you find the current local time and the time difference between various regions."
      },
      {
        question: "Is it safe to travel alone?",
        answer:
          "Traveling alone can be safe and rewarding if you take proper precautions. Research your destination thoroughly, understanding local customs, safety issues, and areas to avoid. Plan your trip carefully, including your accommodation and transportation. Stay connected with family or friends, sharing your plans and whereabouts. Secure your belongings with a money belt or secure bag and be mindful of pickpockets. Stay aware of your surroundings and trust your instincts. Carry necessary medications and know how to access healthcare if needed. Familiarize yourself with local emergency numbers and the location of your nearest embassy or consulate. Respect local customs and stay informed about local news and safety alerts. Many people travel alone without issues, but it’s essential to be proactive and prepared to minimize risks."
      },
      {
        question: "What is the emergency number?",
        answer:
          "Emergency numbers vary by country and region. Here are some common emergency numbers for various locations: - **United States and Canada**: 911 - **United Kingdom**: 999 or 112 - **European Union**: 112 - **Australia**: 000- **New Zealand**: 111 - **Japan**: 110 (police), 119 (fire and medical emergencies) - **China**: 110 (police), 120 (medical emergencies), 119 (fire) - **India**: 112 For specific countries or regions, it's best to check local sources or official government websites for the most accurate emergency contact numbers."
      },
      {
        question: "Can I use my mobile phone?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "What are the business hours?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "Is tipping customary?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      }
    ],
    geography_faqs: [
      {
        question: "What is the highest mountain?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "Which rivers flow through the city?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade."
      },
      {
        question: "What is the climate like?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "Are there any national parks?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "What is the local wildlife?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "What are the main geographical features?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      },
      {
        question: "Is the area prone to natural disasters?",
        answer:
          "Currency, the medium of exchange that facilitates trade, varies widely across the globe, encompassing a diverse array of units each with its unique attributes and historical significance. For instance, in the United States, the dominant currency is the US Dollar (USD), which plays a crucial role not only domestically but also in global financial markets as a standard for international trade and finance. Similarly, the Euro (EUR) is used across the Eurozone, encompassing many countries within the European Union, such as Germany, France, and Italy. The Euro's introduction was a significant step towards economic integration in Europe, providing a single currency for a large economic bloc.In the United Kingdom, the Pound Sterling (GBP) serves as the national currency, often symbolized by the '£' sign, and is known for its long history and stability. The Pound has been a cornerstone in British trade and finance for centuries, reflecting the country's rich economic heritage. Japan utilizes the Yen (JPY), symbolized by '¥', which is crucial for the country's robust economy and serves as a key player in the global foreign exchange market.Emerging economies have their currencies as well; for example, the Indian Rupee (INR) represents India's economic activities and is symbolized by '₹'. In China, the Renminbi (RMB), often referred to by its unit, the Yuan (CNY), is used, reflecting the country's significant role in the global economy. Each of these currencies reflects the economic realities and historical contexts of their respective countries, contributing to the rich tapestry of global financial systems.Additionally, countries with smaller economies or specific regions may have unique currencies such as the Swiss Franc (CHF) in Switzerland, which is renowned for its stability and reliability, or the Australian Dollar (AUD), used in Australia and some Pacific Island nations. Each currency not only facilitates domestic transactions but also plays a role in international trade"
      }
    ]
  });
}
