//***************************home_actions***************************** */
export const FETCH_INTERESTS_REQUEST = "FETCH_INTERESTS_REQUEST";
export const FETCH_INTERESTS_SUCCESS = "FETCH_INTERESTS_SUCCESS";
export const FETCH_INTERESTS_FAILURE = "FETCH_INTERESTS_FAILURE";
export const FETCH_POPULAR_COUNTRIES_REQUEST =
  "FETCH_POPULAR_COUNTRIES_REQUEST";
export const FETCH_POPULAR_COUNTRIES_SUCCESS =
  "FETCH_POPULAR_COUNTRIES_SUCCESS";
export const FETCH_POPULAR_COUNTRIES_FAILURE =
  "FETCH_POPULAR_COUNTRIES_FAILURE";
export const FETCH_RECENT_ADDITIONS_REQUEST = "FETCH_RECENT_ADDITIONS_REQUEST";
export const FETCH_RECENT_ADDITIONS_SUCCESS = "FETCH_RECENT_ADDITIONS_SUCCESS";
export const FETCH_RECENT_ADDITIONS_FAILURE = "FETCH_RECENT_ADDITIONS_FAILURE";
export const FETCH_PLACES_REQUEST = "FETCH_PLACES_REQUEST";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_FAILURE = "FETCH_PLACES_FAILURE";
export const FETCH_FAVOURITE_PLACES_REQUEST = "FETCH_FAVOURITE_PLACES_REQUEST";
export const FETCH_FAVOURITE_PLACES_SUCCESS = "FETCH_FAVOURITE_PLACES_SUCCESS";
export const FETCH_FAVOURITE_PLACES_FAILURE = "FETCH_FAVOURITE_PLACES_FAILURE";
//***************************aboutus_actions***************************** */
export const FETCH_SITE_INFO_REQUEST = "FETCH_SITE_INFO_REQUEST";
export const FETCH_SITE_INFO_SUCCESS = "FETCH_SITE_INFO_SUCCESS";
export const FETCH_SITE_INFO_FAILURE = "FETCH_SITE_INFO_FAILURE";
//***************************faq_actions***************************** */
export const FETCH_FAQ_REQUEST = "FETCH_FAQ_REQUEST";
export const FETCH_FAQ_SUCCESS = "FETCH_FAQ_SUCCESS";
export const FETCH_FAQ_FAILURE = "FETCH_FAQ_FAILURE";
//***************************donate_actions***************************** */
export const FETCH_DONATE_REQUEST = "FETCH_DONATE_REQUEST";
export const FETCH_DONATE_SUCCESS = "FETCH_DONATE_SUCCESS";
export const FETCH_DONATE_FAILURE = "FETCH_DONATE_FAILURE";
//***************************contact_actions***************************** */
export const FETCH_CONTACT_REQUEST = "FETCH_CONTACT_REQUEST";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
export const FETCH_CONTACT_FAILURE = "FETCH_CONTACT_FAILURE";
export const POST_NOTE_REQUEST = "POST_NOTE_REQUEST";
export const POST_NOTE_SUCCESS = "POST_NOTE_SUCCESS";
export const POST_NOTE_FAILURE = "POST_NOTE_FAILURE";
//***************************job_actions***************************** */
export const FETCH_JOB_OPTIONS_REQUEST = "FETCH_JOB_OPTIONS_REQUEST";
export const FETCH_JOB_OPTIONS_SUCCESS = "FETCH_JOB_OPTIONS_SUCCESS";
export const FETCH_JOB_OPTIONS_FAILURE = "FETCH_JOB_OPTIONS_FAILURE";
export const FETCH_JOB_RESULTS_REQUEST = "FETCH_JOB_RESULTS_REQUEST";
export const FETCH_JOB_RESULTS_SUCCESS = "FETCH_JOB_RESULTS_SUCCESS";
export const FETCH_JOB_RESULTS_FAILURE = "FETCH_JOB_RESULTS_FAILURE";
export const FETCH_JOB_DETAIL_REQUEST = "FETCH_JOB_DETAIL_REQUEST";
export const FETCH_JOB_DETAIL_SUCCESS = "FETCH_JOB_DETAIL_SUCCESS";
export const FETCH_JOB_DETAIL_FAILURE = "FETCH_JOB_DETAIL_FAILURE";
//***************************news_actions***************************** */
export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";
export const FETCH_NEW_REQUEST = "FETCH_NEW_REQUEST";
export const FETCH_NEW_SUCCESS = "FETCH_NEW_SUCCESS";
export const FETCH_NEW_FAILURE = "FETCH_NEW_FAILURE";
export const FETCH_TRENDS_REQUEST = "FETCH_TREND_REQUEST";
export const FETCH_TRENDS_SUCCESS = "FETCH_TREND_SUCCESS";
export const FETCH_TRENDS_FAILURE = "FETCH_TREND_FAILURE";
//***************************event_actions***************************** */
export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const FETCH_EVENT_REQUEST = "FETCH_EVENT_REQUEST";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_FAILURE = "FETCH_EVENT_FAILURE";
export const FETCH_GROUPS_REQUEST = "FETCH_GROUPS_REQUEST";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";
export const FETCH_RECOMMENDED_REQUEST = "FETCH_RECOMMENDED_REQUEST";
export const FETCH_RECOMMENDED_SUCCESS = "FETCH_RECOMMENDED_SUCCESS";
export const FETCH_RECOMMENDED_FAILURE = "FETCH_RECOMMENDED_FAILURE";
export const FETCH_COMMUNITIES_REQUEST = "FETCH_COMMUNITIES_REQUEST";
export const FETCH_COMMUNITIES_SUCCESS = "FETCH_COMMUNITIES_SUCCESS";
export const FETCH_COMMUNITIES_FAILURE = "FETCH_COMMUNITIES_FAILURE";
//***************************user_actions***************************** */
export const FETCH_USER_PROFILE_REQUEST = "FETCH_USER_PROFILE_REQUEST";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILURE = "FETCH_USER_PROFILE_FAILURE";
