//***************************photo_actions***************************** */
export const FETCH_INTERESTS_REQUEST = "FETCH_INTERESTS_REQUEST";
export const FETCH_INTERESTS_SUCCESS = "FETCH_INTERESTS_SUCCESS";
export const FETCH_INTERESTS_FAILURE = "FETCH_INTERESTS_FAILURE";
export const FETCH_POPULAR_COUNTRIES_REQUEST =
  "FETCH_POPULAR_COUNTRIES_REQUEST";
export const FETCH_POPULAR_COUNTRIES_SUCCESS =
  "FETCH_POPULAR_COUNTRIES_SUCCESS";
export const FETCH_POPULAR_COUNTRIES_FAILURE =
  "FETCH_POPULAR_COUNTRIES_FAILURE";
