//***************************home_actions***************************** */
export const FETCH_INTERESTS_REQUEST = "FETCH_INTERESTS_REQUEST";
export const FETCH_INTERESTS_SUCCESS = "FETCH_INTERESTS_SUCCESS";
export const FETCH_INTERESTS_FAILURE = "FETCH_INTERESTS_FAILURE";
export const FETCH_POPULAR_COUNTRIES_REQUEST =
  "FETCH_POPULAR_COUNTRIES_REQUEST";
export const FETCH_POPULAR_COUNTRIES_SUCCESS =
  "FETCH_POPULAR_COUNTRIES_SUCCESS";
export const FETCH_POPULAR_COUNTRIES_FAILURE =
  "FETCH_POPULAR_COUNTRIES_FAILURE";
export const FETCH_RECENT_ADDITIONS_REQUEST = "FETCH_RECENT_ADDITIONS_REQUEST";
export const FETCH_RECENT_ADDITIONS_SUCCESS = "FETCH_RECENT_ADDITIONS_SUCCESS";
export const FETCH_RECENT_ADDITIONS_FAILURE = "FETCH_RECENT_ADDITIONS_FAILURE";
export const FETCH_PLACES_REQUEST = "FETCH_PLACES_REQUEST";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_FAILURE = "FETCH_PLACES_FAILURE";

//***************************aboutus_actions***************************** */
export const FETCH_SITE_INFO_REQUEST = "FETCH_SITE_INFO_REQUEST";
export const FETCH_SITE_INFO_SUCCESS = "FETCH_SITE_INFO_SUCCESS";
export const FETCH_SITE_INFO_FAILURE = "FETCH_SITE_INFO_FAILURE";
//***************************faq_actions***************************** */
export const FETCH_FAQ_REQUEST = "FETCH_FAQ_REQUEST";
export const FETCH_FAQ_SUCCESS = "FETCH_FAQ_SUCCESS";
export const FETCH_FAQ_FAILURE = "FETCH_FAQ_FAILURE";
// //***************************donate_actions***************************** */
// export const FETCH_FAQ_REQUEST = "FETCH_FAQ_REQUEST";
// export const FETCH_FAQ_SUCCESS = "FETCH_FAQ_SUCCESS";
// export const FETCH_FAQ_FAILURE = "FETCH_FAQ_FAILURE";
